[[redirects]]
from = "/parking-jawn"
to = "https://www.parkingjawn.com/"
force = true
status = 200

[[redirects]]
from = "/philly-gun-violence-map"
to = "https://phillygunviolence.netlify.app/philly-gun-violence-map/"
force = true
status = 200

[[redirects]]
from = "/philly-gun-violence-map/*"
to = "https://phillygunviolence.netlify.app/philly-gun-violence-map/:splat"
force = true
status = 200

[[redirects]]
from = "/mapping-gun-violence"
to = "/philly-gun-violence-map"
status = 301
